# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(verbose_name='Білет'),
        ),
    ]
